export { default as MyPortfolioView } from "./MyPortfolioView";
export { default as About } from "./About";
export { default as Project } from "./Project";
export { default as Experience } from "./Experience";
export { default as Skills } from "./Skills";
export { default as Footer } from "./layout/Footer";
export { default as NavBar } from "./layout/NavBar";
export { default as Contact } from "./Contact";
export { default as PhotoGallery } from "./PhotoGallery";
